### ISSUE TITLE
/index.html

### ISSUE THREAD

**Issue by JohnGe** [metachris/appengine-boilerplate#1]
Hi,

In advance, thank you for your repository, it's very interresting.

As I was browsing the files, I may have found some unwanted behavior.
Stop me if I'm wrong, but according to your app.yaml, if someone go to the url : /index.html , the static/index.html file will be sent to the browser, no ?

**Comment by metachris** [comment]
Yes, if you keep this configuration in app.yaml, it will redirect all requests for URL's ending in `.html` to `/static/`.
